### ISSUE TITLE
NA's when reading integrated XDS files - function readXDS

### ISSUE THREAD

**Issue by jfoadi** [jfoadi/cry#1]
Dear Rita,
when I read an integrated XDS file some of the middle columns have name NA. It's like there is no internal way of controlling how many data columns are included. This doesn't seem to be the case for XDS scaled files.

**Comment by ritagior** [comment]
Dear James, as integrated XDS file do you mean  the file INTEGRATE.HKL? The function readXDS for the moment read only the XDS_ASCII.HKL files this is the reason because you see the NA as column name for some columns. I will fix the issue.

**Comment by jfoadi** [comment]
I think I have now sorted that issue. There is now just one readXDS_ASCII that reads files from both XDS and XSCALE. Reading a few files does not seem to raise any NA's.
